# Generated by Django 3.1.4 on 2020-12-27 05:45

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20201224_1840'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
