# Generated by Django 3.1.4 on 2021-01-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_comments_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='restrict_comments',
            field=models.BooleanField(default=False),
        ),
    ]
